Wait for rabbitmq before starting lma_collector
If we start lma_collector before the availability of rabbitmq cluster it
will fail to connect to the lma queues and then, it will fail to start.
It may take several long minutes before pacemaker starts the service.
So we need to be sure that rabbitmq cluster is up and running before
starting lma_collector.

Change-Id: Ia254b744f4173f64ee3ab8200b2896ecc412d06f

diff --git a/deployment_scripts/puppet/modules/heka/templates/hekad.upstart.conf.erb b/deployment_scripts/puppet/modules/heka/templates/hekad.upstart.conf.erb
--- a/deployment_scripts/puppet/modules/heka/templates/hekad.upstart.conf.erb
+++ b/deployment_scripts/puppet/modules/heka/templates/hekad.upstart.conf.erb
@@ -9,6 +9,26 @@ respawn
 
 <% unless @run_as_root -%>
 pre-start script
+    # We must wait that rabbitmq is started before running.
+    # We can not rely on /var/run/rabbitmq/p_pid because it only means that
+    # beam is running.
+
+    # Don't exit if command failed. Instead catch it and log the error.
+    set +e
+    RABBITMQCTL=$(which rabbitmqctl 2>/dev/null)
+    set -e
+
+    if [ -z $RABBITMQCTL ]; then
+        echo "$(date +"%Y/%m/%d %H:%M:%S") ERROR: rabbitmqctl not found"
+        exit 1
+    fi
+
+    while ! $RABBITMQCTL cluster_status >/dev/null 2>&1
+    do
+        echo "$(date +"%Y/%m/%d %H:%M:%S") Waiting for RabbitMQ availability..."
+        sleep 60
+    done
+
     touch <%= @log_file %>
     chown <%= @heka_user %>:<%= @heka_user %> <%= @log_file %>
 end script
